In [1]:
import os

In [5]:
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csy')
with open(data_file, 'w') as f:
    f.write('NumberRooms, Alley, Price\n')  # 列名
    f.write('NA, Pave, 127500\n')  # 每行表示一个数据样本
    f.write('2, NA, 106000\n')
    f.write('4, NA, 178100\n')
    f.write('NA, NA, 140000\n')

In [6]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumberRooms  Alley   Price
0          NaN   Pave  127500
1          2.0     NA  106000
2          4.0     NA  178100
3          NaN     NA  140000


In [7]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
print(inputs)

   NumberRooms  Alley
0          NaN   Pave
1          2.0     NA
2          4.0     NA
3          NaN     NA


In [8]:
print(outputs)

0    127500
1    106000
2    178100
3    140000
Name:  Price, dtype: int64


In [9]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumberRooms   Alley_ NA   Alley_ Pave   Alley_nan
0          NaN           0             1           0
1          2.0           1             0           0
2          4.0           1             0           0
3          NaN           1             0           0


In [10]:
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[nan, 0., 1., 0.],
         [2., 1., 0., 0.],
         [4., 1., 0., 0.],
         [nan, 1., 0., 0.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

[[nan  0.  1.  0.]
 [ 2.  1.  0.  0.]
 [ 4.  1.  0.  0.]
 [nan  1.  0.  0.]]


In [17]:
data_file = os.path.join('..', 'data', 'job_house_tiny.csy')
with open(data_file, 'w') as f:
    f.write('NumberRooms, Alley, Price\n')  # 列名
    f.write('NA, Pave, 127500\n')  # 每行表示一个数据样本
    f.write('2, NA, 106000\n')
    f.write('4, NA, 178100\n')
    f.write('NA, NA, 140000\n')
    f.write('NA, Pave, 240000\n')
    f.write('NA, NA, nan\n')
    f.write('5, NA, 140000\n')
    f.write('2, Pave, nan\n')
    f.write('NA, NA, 500000\n')

In [19]:
data = pd.read_csv('../data/job_house_tiny.csy')
inputs = data.iloc[:, 0:2]
data = pd.get_dummies(inputs, dummy_na=True)
data

NumberRooms   Alley_ NA   Alley_ Pave   Alley_nan
0          NaN           0             1           0
1          2.0           1             0           0
2          4.0           1             0           0
3          NaN           1             0           0
4          NaN           0             1           0
5          NaN           1             0           0
6          5.0           1             0           0
7          2.0           0             1           0
8          NaN           1             0           0