In [1]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x +y, x*y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
x[3]

tensor(3)

In [4]:
x = torch.arange(9).reshape(3,3)

In [5]:
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
len(x)

3

In [7]:
x.shape

torch.Size([3, 3])

In [8]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
B.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
B.shape

torch.Size([3, 3])

In [11]:
A = torch.arange(12).reshape(3,4)

In [12]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
A * B

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [15]:
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [16]:
B + 1

tensor([[2, 3, 4],
        [3, 1, 5],
        [4, 5, 6]])

In [17]:
B.sum()

tensor(24)

In [19]:
B.sum(dim=1)

tensor([ 6,  6, 12])

In [20]:
B.sum(dim=[0, 1])

tensor(24)

In [25]:
B = torch.arange(12, dtype=torch.float32).reshape(3,4)
B.mean(), B.sum() / A.numel()

(tensor(5.5000), tensor(5.5000))

In [26]:
B.mean(axis=0), B.sum(axis=0) / B.shape[0]

(tensor([4., 5., 6., 7.]), tensor([4., 5., 6., 7.]))

In [27]:
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
B.sum(0)  # 把每一列对应的三行进行求和。，就是求和所有行的值。

tensor([12., 15., 18., 21.])

In [29]:
B.sum(dim=0)

tensor([12., 15., 18., 21.])

In [30]:
B.sum(axis=0)

tensor([12., 15., 18., 21.])

In [31]:
B.sum(1)

tensor([ 6., 22., 38.])

In [32]:
# 非降维求和
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.]])

In [33]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [37]:
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.]])

In [38]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
# 由于sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A除以sum_A
A/sum_A  # 优雅，太优雅了。

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895]])

In [40]:
# 2.3.7 点积（Dot Product）
x, y = torch.arange(4, dtype=torch.float32), torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [41]:
torch.sum(x * y)

tensor(6.)

In [42]:
A.shape

torch.Size([3, 4])

In [43]:
x.shape

torch.Size([4])

In [45]:
torch.mv(A, x).shape

torch.Size([3])

In [46]:
# 2.3.9 矩阵-矩阵乘法

In [47]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

2

In [50]:
torch.abs(u).sum()

tensor(7.)

In [51]:
torch.norm(torch.ones(4, 9))

tensor(6.)

In [52]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [55]:
A = A.reshape(2, 2, 3)

In [57]:
A

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [58]:
len(A)

2

In [59]:
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [60]:
len(B)

3

In [65]:
B / B.sum(1, keepdim=True)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895]])

In [71]:
C = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
C

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [70]:
C.sum(0).shape

torch.Size([3, 4])

In [68]:
C.sum(1)

tensor([[12., 15., 18., 21.],
        [48., 51., 54., 57.]])

In [69]:
C.sum(2)

tensor([[ 6., 22., 38.],
        [54., 70., 86.]])

In [72]:
torch.linalg.norm(C)

tensor(65.7571)

In [73]:
a = torch.tensor([1, 2])
a.pow(2)

tensor([1, 4])