In [1]:
# 不带参数的层
import torch
import torch.nn.functional as F
from torch import nn

In [3]:
class CenterLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [4]:
layer = CenterLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
# 现在我们可以将层作为组件合并到更复杂的模型中。
net = nn.Sequential(nn.Linear(8, 128), CenterLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.6566e-10, grad_fn=<MeanBackward0>)

In [9]:
# 带参数的层
print(torch.randn(3,))
print(torch.randn(3))

tensor([ 0.1057, -0.0909, -0.4273])
tensor([-0.3239, -0.4717, -0.9708])


In [10]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [11]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.0564,  0.8768, -0.5989],
        [ 1.2279, -1.0398,  1.1849],
        [-0.2229, -1.5669,  1.8368],
        [-1.4362,  0.1146,  0.5914],
        [ 1.5634,  0.5408, -0.0710]], requires_grad=True)

In [12]:
linear(torch.rand(2, 5))

tensor([[1.1589, 0.0000, 1.5587],
        [1.2801, 0.0000, 0.0000]])

In [13]:
# 我们还可以使用自定义层构建模型，就像使用内置的全连接层一样使用自定义层

In [15]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[3.9139],
        [1.1735]])