In [1]:
# 加载和保存张量
# 对于单个张量，我们可以直接调用load和save函数分别读写它们。这两个函数都要求我们提供一个名称，save要求将要保存的变量
# 作为输入

In [2]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file')

In [3]:
# 我们现在可以将存储在文件中的数据读回内存
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [4]:
# 我们可以存储一个张量列表，然后把它们读回内存
y = torch.zeros(4)
torch.save([x, y], 'x-file')
x2, y2 = torch.load('x-file')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [5]:
# 我们甚至可以写入或读取从字符映射到张量的字典。当我们要读取或写入模型中的权重时，这很方便。

In [6]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [7]:
# 加载和保存模型参数

In [8]:
"""
保存单个权重向量（或其他张量）确实游泳，但是如果我们想保存整个模型，并在以后加载它们，单独保存每个向量则会变得很麻烦。毕竟
我们可能有数百个参数散布在各处。因此，深度学习框架提供了内置函数来保存和加载整个网络。因为需要注意的一个重要细节时，这将保存模型的参数而不是保存整个模型。例如，我们有一个三层多层感知机，我们需要单独指定架构。因为模型本身可以包含任意代码，所以模型本身难以序列化。因此，为了恢复模型，我们需要用代码生成架构，然后从磁盘加载参数。
"""

'\n保存单个权重向量（或其他张量）确实游泳，但是如果我们想保存整个模型，并在以后加载它们，单独保存每个向量则会变得很麻烦。毕竟\n我们可能有数百个参数散布在各处。因此，深度学习框架提供了内置函数来保存和加载整个网络。因为需要注意的一个重要细节时，这将保存模型的参数而不是保存整个模型。例如，我们有一个三层多层感知机，我们需要单独指定架构。因为模型本身可以包含任意代码，所以模型本身难以序列化。因此，为了恢复模型，我们需要用代码生成架构，然后从磁盘加载参数。\n'

In [10]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [11]:
torch.save(net.state_dict(), 'mlp.params')

In [12]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [13]:
# 由于两个实例具有相同的模型参数，在输入相同的X时，两个实例的计算结果应该相同

In [14]:
Y_clone= clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])